token = "" # Bot token
guildId = "" # Your server id
clientId = "" # For commands

[tempRole]
enabled = true
rolesId = [ "" ] # Roles that will be assigned on first login
roleDuration = 72 # In hours, how much time until role expires
checkInterval = 2 # In hours, time interval between checks

[moderation]
enabled = true
roles = [ "" ] # Moderator roles
checkInterval = 2 # In hours, time interval between checks
[moderation.warn]

# This will act as both the maximum amount of warns and which roles will be given when using the warn command
rolesId = [ "", "" ]
banAfterLimit = false # If the bot should ban the user after reaching the maximum amount of warns
banMessage = "You've been warn one too many time"
canExpire = true # If the warn is supposed to expire after a given amount of time
expiresAfter = 72 # In hours, how much time until role expires

[autorole]
enabled = true
channel = ""
rolesId = [ "", "" ]