services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres

  whodb:
    image: clidey/whodb
    ports:
      - "8080:8080"

  discord_bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./config:/usr/src/app/config
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_URL: "postgres://postgres:postgres@db:5432/postgres"
