CREATE TABLE IF NOT EXISTS temp_roles (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS warn (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    given_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)

CREATE TABLE IF NOT EXISTS auto_temp_roles (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    given_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)