CREATE TABLE IF NOT EXISTS warns (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    given_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)

CREATE TABLE IF NOT EXISTS auto_temp_roles (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    given_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)

CREATE TABLE IF NOT EXISTS manual_roles (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    given_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)